
set(FILES
    Source/DioramaModuleInterface.cpp
    Source/DioramaModuleInterface.h
    Source/Clients/DioramaAssetUtils.h
    Source/Clients/DioramaSystemComponent.cpp
    Source/Clients/DioramaSystemComponent.h
    Source/Clients/SpriteComponent.cpp
    Source/Clients/SpriteComponent.h
    Source/Clients/SpriteComponentConfig.cpp
    Source/Clients/SpriteBus.cpp
    Source/Clients/SpriteRequestHandler.cpp
    Source/Clients/SpriteRequestHandler.h
    Source/Clients/SpriteAnimation.h
    Source/Clients/SpriteBatchPlan.h
    Source/Clients/SkeletalClip.h
    Source/Clients/AsepriteImport.h
    Source/Clients/AsepriteImport.cpp
    Source/Clients/AsepriteBinary.h
    Source/Clients/AsepriteBinary.cpp
    Source/Clients/Collision2D.h
    Source/Clients/Collision2DBus.cpp
    Source/Clients/Collision2DSystemComponent.cpp
    Source/Clients/Collision2DSystemComponent.h
    Source/Clients/Collider2DComponent.cpp
    Source/Clients/Collider2DComponent.h
    Source/Clients/Camera2D.h
    Source/Clients/Particles2D.h
    Source/Clients/UILayout2D.h
    Source/Clients/SpriteFeatureProcessor.cpp
    Source/Clients/SpriteFeatureProcessor.h
    Source/Clients/SpritePresenter.cpp
    Source/Clients/SpritePresenter.h
    Source/Clients/DioramaLightComponent.cpp
    Source/Clients/DioramaLightComponent.h
    Source/Clients/LightPresenter.cpp
    Source/Clients/LightPresenter.h
    Source/Clients/LightBus.cpp
    Source/Clients/LightRequestHandler.cpp
    Source/Clients/LightRequestHandler.h
    Source/Clients/DioramaCamera2DComponent.cpp
    Source/Clients/DioramaCamera2DComponent.h
    Source/Clients/CameraBus.cpp
    Source/Clients/ParticleEmitterComponent.cpp
    Source/Clients/ParticleEmitterComponent.h
    Source/Clients/ParticleBus.cpp
    Source/Clients/DioramaUIComponent.cpp
    Source/Clients/DioramaUIComponent.h
    Source/Clients/UIBus.cpp
    Source/Clients/AudioBus.cpp
    Source/Clients/DioramaCRTComponent.cpp
    Source/Clients/DioramaCRTComponent.h
    Source/Clients/CRTBus.cpp
    Source/Clients/DioramaLookComponent.cpp
    Source/Clients/DioramaLookComponent.h
    Source/Clients/LookBus.cpp
    Source/Clients/DioramaSkeletalClipComponent.cpp
    Source/Clients/DioramaSkeletalClipComponent.h
    Source/Clients/SkeletalBus.cpp
    Source/Clients/DioramaAsepriteComponent.cpp
    Source/Clients/DioramaAsepriteComponent.h
    Source/Clients/AsepriteBus.cpp
    Source/Clients/TilemapPaint.h
    Source/Clients/TilemapAutotile.h
    Source/Clients/DioramaParallaxComponent.cpp
    Source/Clients/DioramaParallaxComponent.h
    Source/Clients/ParallaxBus.cpp
    Source/Clients/TilemapComponent.cpp
    Source/Clients/TilemapComponent.h
    Source/Clients/TilemapComponentConfig.cpp
    Source/Clients/TilemapBus.cpp
    Source/Clients/TilemapRequestHandler.cpp
    Source/Clients/TilemapRequestHandler.h
    Source/Clients/TilemapPresenter.cpp
    Source/Clients/TilemapPresenter.h
)
