
set(FILES
    Source/Tools/DioramaEditorSystemComponent.cpp
    Source/Tools/DioramaEditorSystemComponent.h
    Source/Tools/EditorSpriteComponent.cpp
    Source/Tools/EditorSpriteComponent.h
    Source/Tools/EditorTilemapComponent.cpp
    Source/Tools/EditorTilemapComponent.h
    Source/Tools/EditorCollider2DComponent.cpp
    Source/Tools/EditorCollider2DComponent.h
    Source/Tools/EditorDioramaLightComponent.cpp
    Source/Tools/EditorDioramaLightComponent.h
    Source/Tools/EditorDioramaCamera2DComponent.cpp
    Source/Tools/EditorDioramaCamera2DComponent.h
    Source/Tools/EditorParticleEmitterComponent.cpp
    Source/Tools/EditorParticleEmitterComponent.h
    Source/Tools/EditorDioramaParallaxComponent.cpp
    Source/Tools/EditorDioramaParallaxComponent.h
    Source/Tools/EditorDioramaCRTComponent.cpp
    Source/Tools/EditorDioramaCRTComponent.h
    Source/Tools/EditorDioramaLookComponent.cpp
    Source/Tools/EditorDioramaLookComponent.h
    Source/Tools/EditorDioramaSkeletalClipComponent.cpp
    Source/Tools/EditorDioramaSkeletalClipComponent.h
    Source/Tools/EditorDioramaInputComponent.cpp
    Source/Tools/EditorDioramaInputComponent.h
    Source/Tools/EditorDioramaHitboxComponent.cpp
    Source/Tools/EditorDioramaHitboxComponent.h
    Source/Tools/EditorDioramaBulletEmitterComponent.cpp
    Source/Tools/EditorDioramaBulletEmitterComponent.h
    Source/Tools/EditorDioramaDepthBodyComponent.cpp
    Source/Tools/EditorDioramaDepthBodyComponent.h
    Source/Tools/EditorDioramaDayNightComponent.cpp
    Source/Tools/EditorDioramaDayNightComponent.h
    Source/Tools/EditorDioramaAnimStateMachineComponent.cpp
    Source/Tools/EditorDioramaAnimStateMachineComponent.h
    Source/Tools/EditorDioramaAsepriteComponent.cpp
    Source/Tools/EditorDioramaAsepriteComponent.h
    Source/Tools/EditorTilemapPaintComponentMode.cpp
    Source/Tools/EditorTilemapPaintComponentMode.h
    Source/Tools/TilemapPaintEditorBus.h
    Source/Builders/DioramaAsepriteBuilder.cpp
    Source/Builders/DioramaAsepriteBuilder.h
    Source/Builders/DioramaTilemapBuilder.cpp
    Source/Builders/DioramaTilemapBuilder.h
    Source/Builders/DioramaBuilderComponent.cpp
    Source/Builders/DioramaBuilderComponent.h
)
