
set(FILES
    Tests/Clients/DioramaTest.cpp
    Tests/Clients/TilemapTest.cpp
    Tests/Clients/Collision2DTest.cpp
    Tests/Clients/Collision2DSystemTest.cpp
    Tests/Clients/Camera2DTest.cpp
    Tests/Clients/Particles2DTest.cpp
    Tests/Clients/SpriteCullTest.cpp
    Tests/Clients/AsepriteBinaryTest.cpp
    Tests/Clients/TilemapV2Test.cpp
    Tests/Clients/InputActionMapTest.cpp
    Tests/Clients/MotionInputTest.cpp
    Tests/Clients/HitboxFramesTest.cpp
    Tests/Clients/DioramaHitboxComponentTest.cpp
    Tests/Clients/BulletPatternTest.cpp
    Tests/Clients/DioramaBulletEmitterComponentTest.cpp
    Tests/Clients/AnimStateMachineTest.cpp
    Tests/Clients/DioramaTestMain.cpp
)
